### ISSUE TITLE
seq should be an optional dependency in opam

### ISSUE THREAD

**Issue by hcarty** [ocamllibs/stdcompat#3]
Otherwise stdcompat doesn't properly take advantage of the type compatibility seq provides if seq is installed after stdcompat.

**Comment by thierry-martinez** [comment]
Thank you! It was done in https://github.com/thierry-martinez/stdcompat/blob/dbb2e6a46e2d4ff4cd978ab8cfff82d76f4e80fb/stdcompat.opam#L15 but I forgot to report this line in https://github.com/ocaml/opam-repository/ . Done in https://github.com/ocaml/opam-repository/pull/12090 .

**Comment by hcarty** [comment]
Oh thank you! I apologize, I should have checked the opam file here first.
