### ISSUE TITLE
Please clarify the license of the repository

### ISSUE THREAD

**Issue by edwintorok** [ocamllibs/stdcompat#5]
The opam file claims it is BSD, the repository claims it is GPL in the COPYING file.
There are a lot of MIT/LGPL/etc. licenses packages on opam, I think it would be beneficial if a compatibility library's license would be the same as the compiler's, or less restrictive. If it is GPL then everything linking it would become GPL too, which would mean some packages couldn't use it if they want to retain their MIT licensing.

**Comment by thierry-martinez** [comment]
Thanks for noticing this! The project was intended to be under BSD license since the beginning, and a `LICENSE` file was provided accordingly. However, automake generated a COPYING file with the GPLv3 by default. The `COPYING` file now contains the BSD license, and the `LICENSE` file is removed.
