### ISSUE TITLE
Is there non tail rec code in there?

### ISSUE THREAD

**Issue by UnixJunkie** [ocamllibs/stdcompat#6]
Hello Thierry,
We are thinking about depending on it for batteries.
Hence the question.
Regards,
F.

**Comment by thierry-martinez** [comment]
I am very glad to hear that you think about using stdcompat for batteries.

There is tail rec code here indeed: implementations provided by stdcompat are very close to those we find in the standard library.

stdcompat could provide tail rec implementations but that would change the purpose of the library (basically, stdcompat is designed just to reexport the standard library as is if OCaml is recent enough).

I think that Batteries could still provide tail rec reimplementations, and only rely on stdcompat if some standard library functions are needed that are not provided in old versions of OCaml that you want to support.

**Comment by UnixJunkie** [comment]
thanks for the info
